export const sportsList = [
  { id: 1, name: "Archery", Form: "Match Form" },
  { id: 2, name: "Athletics", Form: "Match Form" },
  { id: 3, name: "Badminton", Form: "Match Form" },
  { id: 4, name: "Basketball", Form: "Match Form" },
  { id: 5, name: "Bowling", Form: "Match Form" },
  { id: 6, name: "Boxing", Form: "Match Form" },
  { id: 7, name: "Cricket", Form: "Match Form" },
  { id: 8, name: "Cycling", Form: "Match Form" },
  { id: 9, name: "Equestrian", Form: "Match Form" },
  { id: 10, name: "Fencing", Form: "Match Form" },
  { id: 11, name: "Football", Form: "Match Form" },
  { id: 12, name: "Golf", Form: "Match Form" },
  { id: 13, name: "Gymnastics", Form: "Match Form" },
  { id: 14, name: "Hockey", Form: "Match Form" },
  { id: 15, name: "Judo", Form: "Match Form" },
  { id: 16, name: "Karate", Form: "Match Form" },
  { id: 17, name: "MMA (Mixed Martial Arts)", Form: "Match Form" },
  { id: 18, name: "Netball", Form: "Match Form" },
  { id: 19, name: "Rugby", Form: "Match Form" },
  { id: 20, name: "Sailing", Form: "Match Form" },
  { id: 21, name: "Shooting", Form: "Match Form" },
  { id: 22, name: "Skateboarding", Form: "Match Form" },
  { id: 23, name: "Snooker", Form: "Match Form" },
  { id: 24, name: "Squash", Form: "Match Form" },
  { id: 25, name: "Swimming", Form: "Match Form" },
  { id: 26, name: "Table tennis", Form: "Match Form" },
  { id: 27, name: "Volleyball ", Form: "Match Form" },
  { id: 28, name: "Weightlifting  ", Form: "Match Form" },
];
