name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello User, You have decided to embark on this treacherous journey with me, I hope you have fun"
        pr-message: "Hello User, You have decided to embark on this treacherous journey with me, I hope you have fun"
